version: "3.8"

services:
    trafic:
        container_name: traffic_generator
        build: ./Traffic
        networks:
            - net_1
        depends_on:
            - api

    api:
        container_name: api
        build: ./API
        ports:
            - 8000:8000
        networks:
            - net_1

networks:
    net_1:
        driver: bridge
